[project]
name = "bystandereffectmas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mahmoud Saad", email = "S6175767@rug.nl" }
]
requires-python = ">=3.14"
dependencies = [
    "mesa>=3.5.1",
]

[project.scripts]
bystandereffectmas = "bystandereffectmas:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
